-- START: CREATE DATABASE SCRIPT
-- END: CREATE DATABASE SCRIPT


-- START: CREATE TABLES SCRIPT
-- END: CREATE TABLES SCRIPT


-- START: INSERT INITIAL DATA IF NEEDED
-- END: INSERT INITIAL DATA IF NEEDED